### ISSUE TITLE
for derived values, send null on first measurement rather then the current counter

### ISSUE THREAD

**Issue by woodsaj** [intelsdi-x/snap-plugin-collector-mysql#15]
when a task is deleted/re-created the initial measurement sent for rates uses the current counter value, as without a previous value the rate cant be computed.  These sudden potentially very large spikes make graphing the values very difficult

![image](https://cloud.githubusercontent.com/assets/8415072/16260229/05305944-3899-11e6-9004-b9714e47fbc7.png)

Instead of using the potentially large counter value, can null be sent instead for the first seen measurement.

**Comment by lynxbat** [comment]
+1 on this.
