### ISSUE TITLE
"Description" column in METRICS.md

### ISSUE THREAD

**Issue by Armatorix** [intelsdi-x/snap-plugin-collector-mysql#31]
Could you provide description for:
`/intel/mysql/operations/ibuf_merges_discard_merges`
in METRICS.md ?

**Comment by mkleina** [comment]
It seems that this metric does not exist anymore:
https://github.com/mysql/mysql-server/blob/71f48ab393bce80a59e5a2e498cd1f46f6b43f9a/storage/innobase/srv/srv0mon.cc

**Comment by mkleina** [comment]
It seems that this metric does not exist anymore:
https://github.com/mysql/mysql-server/blob/5.7/storage/innobase/srv/srv0mon.cc
